apiVersion: v1
kind: Service
metadata:
  name: marqo-navigator
  namespace: vector-storage
spec:
  type: NodePort
  selector:
    app: marqo-navigator
  ports:
    - port: 9882
      targetPort: 9882
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marqo-navigator
  namespace: vector-storage
  labels:
    app: marqo-navigator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marqo-navigator
  template:
    metadata:
      labels:
        app: marqo-navigator
    spec:
      containers:
      - name: marqo-navigator
        image: viljarfivexer/marqo-navigator:v0.1.13
        imagePullPolicy: Always
        command: ["node", "--experimental-modules", "./runtime/proxy/index.mjs"]
        env:
          - name: MARQO_API_URL
            value: "http://marqo.vector-storage.svc.cluster.local:8882"
          - name: K8S_NAMESPACE
            value: "vector-storage"
        ports:
        - containerPort: 9882