apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: vector-storage
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8443
  selector:
    app: code-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: vector-storage
spec:
  selector:
    matchLabels:
      app: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: linuxserver/code-server:4.96.4
        name: code-server
        env:
          - name: PASSWORD
            value: "password"
          - name: SUDO_PASSWORD
            value: "password"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
        - containerPort: 8443
          name: code-server
        - containerPort: 9882
          name: navigator-proxy
        volumeMounts:
        - name: pv-code-server
          mountPath: /config
      volumes:
      - name: pv-code-server
        persistentVolumeClaim:
          claimName: pvc-code-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-code-server
  namespace: vector-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi