apiVersion: v1
kind: Service
metadata:
  name: vespa-query-server
  namespace: vector-storage
  labels:
    app: vespa-query-server
spec:
  selector:
    app: vespa-query-server
  ports:
  - name: container
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: config
    port: 19071
    targetPort: 19071
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa-query-server
  namespace: vector-storage
  labels:
    app: vespa-query-server
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: vespa-query-server
  selector:
    matchLabels:
      app: vespa-query-server
  template:
    metadata:
      labels:
        app: vespa-query-server
    spec:
      containers:
      - name: vespa-query-server
        image: vespaengine/vespa:8.396.18
        args: ["services"]
        imagePullPolicy: Always
        env:
        - name: VESPA_CONFIGSERVERS
          value: vespa-configserver-0.vespa-internal.vector-storage.svc.cluster.local,vespa-configserver-1.vespa-internal.vector-storage.svc.cluster.local,vespa-configserver-2.vespa-internal.vector-storage.svc.cluster.local
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 19070
          protocol: TCP
        - containerPort: 19071
      
        # resources:
        #     requests:
        #       memory: "4Gi"
        #       cpu: "2"
        #     limits:
        #       memory: "64Gi"
        #       cpu: "2"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vespa-query-server-pdb
  
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: vespa-query-server
