
apiVersion: v1
kind: Service
metadata:
  name: vespa-content-server
  namespace: vector-storage
  labels:
    app: vespa-feed-server
spec:
  clusterIP: None  # This makes it a headless service
  selector:
    app: vespa-content-server
  ports:
  - name: container
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: config
    port: 19071
    targetPort: 19071
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: vespa-content-server
  namespace: vector-storage
  labels:
    app: vespa-content-server
spec:
  selector:
    app: vespa-content-server
  ports:
  - name: container
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: config
    port: 19071
    targetPort: 19071
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa-content-server
  namespace: vector-storage
  labels:
    app: vespa-content-server
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  serviceName: vespa-content-server
  selector:
    matchLabels:
      app: vespa-content-server
  template:
    metadata:
      labels:
        app: vespa-content-server
    spec:
      initContainers:
      - name: chown-var
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sh", "-c", "chown -R 1000 /opt/vespa/var"]
        volumeMounts:
          - name: vespa-var
            mountPath: /opt/vespa/var
      - name: chown-logs
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sh", "-c", "chown -R 1000 /opt/vespa/logs"]
        volumeMounts:
          - name: vespa-logs
            mountPath: /opt/vespa/logs
      - name: init-sysctl
        image: busybox
        imagePullPolicy: Always
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: workspace-permissions
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sh", "-c", "chown -R 1000 /workspace"]
        volumeMounts:
          - name: vespa-workspace
            mountPath: /workspace
      containers:
      - name: vespa-content-server
        image: vespaengine/vespa:8.396.18
        args: ["services"]
        imagePullPolicy: Always
        env:
        - name: VESPA_CONFIGSERVERS
          value: vespa-configserver-0.vespa-internal.vector-storage.svc.cluster.local,vespa-configserver-1.vespa-internal.vector-storage.svc.cluster.local,vespa-configserver-2.vespa-internal.vector-storage.svc.cluster.local
        securityContext:
          runAsUser: 1000
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 19070
          protocol: TCP
        - containerPort: 19071
        volumeMounts:
        - name: vespa-var
          mountPath: /opt/vespa/var
        - name: vespa-logs
          mountPath: /opt/vespa/logs
        - name: vespa-workspace
          mountPath: /workspace
        # resources:
        #     requests:
        #       memory: "4Gi"
        #       cpu: "2"
        #     limits:
        #       memory: "8Gi"
        #       cpu: "2"
  volumeClaimTemplates:
  - metadata:
      name: vespa-var
      namespace: vector-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 36Gi
      # storageClassName: longhorn
  - metadata:
      name: vespa-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: vespa-workspace
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      # storageClassName: longhorn
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vespa-content-server-pdb
  namespace: vector-storage
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: vespa-content-server
