apiVersion: v1
kind: Service
metadata:
  name: marqo-navigator
  namespace: {{ include "marqo.namespace" . }}
spec:
  type: {{ .Values.marqoNavigator.service.type | default "ClusterIP" }}
  selector:
    app: marqo-navigator
  ports:
    - port: 9882
      targetPort: 9882
      {{- if eq (.Values.marqoNavigator.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.marqoNavigator.service.nodePort | default 30000 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marqo-navigator
  namespace: {{ include "marqo.namespace" . }}
  labels:
    app: marqo-navigator
spec:
  replicas: {{ .Values.marqoNavigator.replicas }}
  selector:
    matchLabels:
      app: marqo-navigator
  template:
    metadata:
      labels:
        app: marqo-navigator
    spec:
      containers:
      - name: marqo-navigator
        image: {{ .Values.marqoNavigator.image }}
        imagePullPolicy: Always
        command: ["node", "--experimental-modules", "./runtime/proxy/index.mjs"]
        env:
          - name: MARQO_API_URL
            value: "http://marqo.{{ include "marqo.namespace" . }}.svc.cluster.local:8882"
          - name: K8S_NAMESPACE
            value: "{{ include "marqo.namespace" . }}"
        ports:
        - containerPort: 9882
          name: http
        {{- if .Values.marqoNavigator.resources }}
        resources:
          {{- toYaml .Values.marqoNavigator.resources | nindent 10 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /
            port: 9882
          initialDelaySeconds: 10
          periodSeconds: 10
