apiVersion: v1
kind: Service
metadata:
  name: marqo-navigator
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: marqo-navigator
  ports:
    - port: 9882
      targetPort: 9882
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marqo-navigator
  namespace: {{ .Values.namespace }}
  labels:
    app: marqo-navigator
spec:
  replicas: {{ .Values.marqoNavigator.replicas }}
  selector:
    matchLabels:
      app: marqo-navigator
  template:
    metadata:
      labels:
        app: marqo-navigator
    spec:
      containers:
      - name: marqo-navigator
        image: {{ .Values.marqoNavigator.image }}
        imagePullPolicy: Always
        command: ["node", "--experimental-modules", "./runtime/proxy/index.mjs"]
        env:
          - name: MARQO_API_URL
            value: "http://marqo.{{ .Values.namespace }}.svc.cluster.local:8882"
          - name: K8S_NAMESPACE
            value: "{{ .Values.namespace }}"
        ports:
        - containerPort: 9882
