apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: {{ include "marqo.namespace" . }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8443
  selector:
    app: code-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  namespace: {{ include "marqo.namespace" . }}
spec:
  replicas: {{ .Values.nodeDevelopment.replicas }}
  selector:
    matchLabels:
      app: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - image: {{ .Values.nodeDevelopment.image }}
        name: code-server
        env:
          - name: PASSWORD
            value: "password"
          - name: SUDO_PASSWORD
            value: "password"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
        ports:
        - containerPort: 8443
          name: code-server
        - containerPort: 9882
          name: navigator-proxy
        volumeMounts:
        - name: pv-code-server
          mountPath: /config
        resources:
          requests:
            memory: {{ .Values.nodeDevelopment.resources.requests.memory }}
            cpu: {{ .Values.nodeDevelopment.resources.requests.cpu }}
          limits:
            memory: {{ .Values.nodeDevelopment.resources.limits.memory }}
            cpu: {{ .Values.nodeDevelopment.resources.limits.cpu }}
      volumes:
      - name: pv-code-server
        persistentVolumeClaim:
          claimName: pvc-code-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-code-server
  namespace: {{ include "marqo.namespace" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
