# Default values for marqo-helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The namespace where resources will be created
# This will be overridden by the -n/--namespace flag when installing the chart
# You only need to set this if deploying resources to a different namespace than the release
namespace: "" 

# Whether to create the namespace if it doesn't exist
# This should be false when using --create-namespace flag with helm install/upgrade
createNamespace: false

# Control whether to create services 
# Set to false when services already exist
createServices: false

# Control whether to install the redundant marqo-app-deployer job
installMarqoAppDeployer: false

# OpenTelemetry configuration
opentelemetry:
  # Whether to deploy the OpenTelemetry collector
  enabled: false
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.103.0"
  mode: deployment
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 400Mi
  # OTLP exporter configuration
  exporter:
    endpoint: "signoz-otel-collector.monitoring.svc.cluster.local:4317"
    tls:
      insecure: true
  # Whether to create cluster role for OTEL collector
  clusterRole:
    create: true

vespaConfigServer:
  replicas: 3
  image: vespaengine/vespa:8.396.18
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 2
  storage:
    var: 8Gi
    logs: 10Gi
    workspace: 10Gi

vespaAdminServer:
  replicas: 1
  image: vespaengine/vespa:8.396.18
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 2
  storage:
    logs: 10Gi

vespaContentServer:
  replicas: 3
  redundancy: 3  # This should match replicas for full redundancy
  image: vespaengine/vespa:8.396.18
  resources:
    requests:
      memory: 4Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 2
  storage:
    var: 36Gi
    logs: 10Gi
    workspace: 10Gi

marqo:
  replicas: 1
  image: marqoai/marqo:2.15.2
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 16Gi
      cpu: 12

marqoNavigator:
  replicas: 1
  image: viljarfivexer/marqo-navigator:v0.1.16
  # Service configuration for Navigator
  service:
    # Can be ClusterIP, NodePort, or LoadBalancer
    type: ClusterIP
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

nodeDevelopment:
  replicas: 0
  image: linuxserver/code-server:4.96.4
  resources:
    requests:
      memory: 2Gi
      cpu: 1
    limits:
      memory: 4Gi
      cpu: 2
