name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'marqo-helm-chart/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        
      # Makes sure the destination directory for charts exists
      - name: Create chart directory
        run: |
          mkdir -p .cr-release-packages
          mkdir -p .cr-index
          
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
        with:
          charts_dir: .
          config: cr.yaml